const users=[
    {
        id:1,
        name:"Sangam",
        email:"Sangam@gmail.com"
    },
    {
        id:2,
        name:"Krishnam",
        email:"Krishnam@gmail.com"
    },
    {
        id:3,
        name:"vivek",
        email:"vivek@gmail.com"
    },
    {
        id:4,
        name:"ballu",
        email:"Ballu@gmail.com"
    },
    {
        id:5,
        name:"chotu",
        email:"chotu@gmail.com"
    },
]

module.exports=users